FROM python:3.10-slim

WORKDIR /app

# Install MLflow
RUN pip install --no-cache-dir mlflow

# Expose MLflow port
EXPOSE 5000

# Command to run the MLflow tracking server using SQLite as backend
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0"]
